version: '3.0'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints: 
          - node.role == manager
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - DB_DATABASE=zabbix
      - POSTGRES_ROOT_PASSWORD=zabbix
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - zabbix-network
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:6.0-ubuntu-latest
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      placement:
        constraints: 
          - "node.role == worker"
    ports:
      - 10051:10051
    networks:
      - zabbix-network
    volumes:
      - zabbix-server:/usr/lib/zabbix
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - DB_SERVER_HOST=postgres
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
      - ZBX_DEBUGLEVEL=3
    depends_on:
      - postgres
  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-apache-pgsql:6.0-ubuntu-latest
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      placement:
        constraints: 
          - "node.role == worker"
    ports:
      - 8080:8080
      - 443:8443
    networks:
      - zabbix-network
    links:
      - postgres
    volumes:
      - zabbix-web:/etc/ssl/apache2
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
      - DB_SERVER_HOST=postgres
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - postgres
networks:
  zabbix-network:
volumes:
  zabbix-server:
  zabbix-web:
  postgres: