services:
  reverse-proxy:
    container_name: reserve-proxy
    image: nginx:1.23-alpine
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - rproxy-sites:/usr/share/nginx
      - rproxy-config:/etc/nginx
    networks:
      - web_teste
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_DATABASE=commerce
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - web_teste
  api:
    container_name: commerce-api
    image: commerce-teste-api:1
    environment:
      - DBUSER=postgres
      - DBHOST=postgres
      - DBPORT=5432
      - DBPW=postgres
      - DBNAME=commerce
    networks:
      - web_teste
    depends_on:
      - postgres
  fastcgi:
    container_name: fastcgi-php
    image: php:8.1.15-fpm-alpine3.17
    networks:
      - web_teste
    depends_on:
      - reverse-proxy
networks:
  web_teste:
    driver: bridge
volumes:
  rproxy-sites:
  rproxy-config:
  db-data: