services:
  reverse-proxy:
    container_name: reserve-proxy
    image: nginx:1.23-alpine
    ports:
      - 8080:80
      - 8081:8080
    volumes:
      - rproxy-sites:/usr/share/nginx
      - rproxy-config:/etc/nginx
    networks:
      - web_teste
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_DATABASE=commerce
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - web_teste
networks:
  web_teste:
    driver: bridge
volumes:
  rproxy-sites:
  rproxy-config:
  db-data: